### PR TITLE
Migrate to use v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
I've tried to migrate to use v0.14 Filter Plugin API.
This PR contains major update change and also includes in breaking changes.
If above questions/problems are acceptable or reasonable for you, could you bump up major version if releasing new version of gem?
And please refer http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12 before release new version.

Thanks.

### CODE REVIEW

**Comment by cosmo0920** [comment]
fluent-plugin-genhashvalue is still using old Fluentd's filter plugin API.
This is an obstacle for using multi workers feature in Fluentd v0.14.

**Comment by takemim** [comment]
Thank you so much.
I will release as soon as possible.

**Comment by mtakemi** [comment]
Thank you so much.
I will release as soon as possible.

**Comment by cosmo0920** [comment]
Awesome. Thanks!

**Pull request merged**
